"""init friend index

Revision ID: 1d26df2fd19c
Revises: af3d9df3db4b
Create Date: 2025-02-21 07:49:52.304055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d26df2fd19c'
down_revision: Union[str, None] = 'af3d9df3db4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_requests',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='unique_user_friend')
    )
    op.create_index('idx_user_friend', 'friend_requests', ['user_id', 'friend_id'], unique=True)
    op.create_index('idx_friends_friend_ids', 'friends', ['friend_ids'], unique=False, postgresql_using='gin')
    op.create_index('idx_friends_user_id', 'friends', ['user_id'], unique=False)
    op.create_foreign_key(None, 'friends', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_index('idx_friends_user_id', table_name='friends')
    op.drop_index('idx_friends_friend_ids', table_name='friends', postgresql_using='gin')
    op.drop_index('idx_user_friend', table_name='friend_requests')
    op.drop_table('friend_requests')
    # ### end Alembic commands ###
